spring:
  config:
    import: classpath:queries.yml
  datasource:
    username: rog
    password: ue
    url: 'jdbc:postgresql://localhost:26257/movr'
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        rewriteBatchedInserts: true
        useConfigs: maxPerformance
      pool-name: local-pool
      maximum-pool-size: 30
      schema: public